version: '3'
services:
  database:
    image: postgres:16
    container_name: cafe
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cafe
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test